root = "./internal"
tmp_dir = "../tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go$"]
exclude_unchanged = false
follow_symlink = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = 500
args_bin = []

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
