FROM golang:1.23.3 AS develop

ARG TARGETOS=linux
ARG TARGETARCH=arm64
ENV TZ=Asia/Tokyo

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./internal ./internal

# 必要なツールのインストール
RUN go install github.com/cosmtrek/air@v1.40.4 && \
    go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install honnef.co/go/tools/cmd/staticcheck@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest

# 自己署名証明書の生成
RUN openssl req -x509 -newkey rsa:2048 -keyout /app/server.key -out /app/server.crt -days 365 -nodes -subj "/CN=localhost"

COPY .air.toml ./

CMD ["air", "-c", ".air.toml"]
